---
- name: Enable Cockpit/Composer/Firewalld/Apache
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: cockpit.socket

- name: Add user to weldr group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: weldr
    append: true

- name: Create a blueprint
  osbuild.composer.create_blueprint:
    dest: "{{ builder_blueprint_src_path }}"
    name: "my-rhel-edge-test"
    version: "0.0.1"
    packages: "{{ builder_compose_pkgs }}"
    customizations: "{{ builder_compose_customizations }}"

- name: Push the blueprint into image builder
  osbuild.composer.push_blueprint:
    src: "{{ builder_blueprint_src_path }}"

- name: Start compose
  osbuild.composer.start_compose:
    blueprint: "my-rhel-edge-test"
    compose_type: "{{ builder_compose_type }}"
  register: compose_start_out

- name: Wait for compose to finish
  osbuild.composer.wait_compose:
    compose_id: "{{ compose_start_out['result']['build_id'] }}"

- name: Export the compose artifact
  osbuild.composer.export_compose:
    compose_id: "{{ compose_start_out['result']['build_id'] }}"
    dest: "/tmp/composer-compose.{{ compose_start_out['result']['output_type'] }}"
