---
- name: Add user to weldr group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: weldr
    append: true
- name: create a blueprint
  osbuild.composer.create_blueprint:
    dest: "{{ blueprint_src_path }}"
    name: "my-rhel-edge-test"
    version: "0.0.1"
    packages:
      - "vim-enhanced"
      - "ansible-core"
      - "git"
    customizations:
      user:
        name: "admiller"
        description: "test user"
        password: "openshift"
        key: "{{ pub_key }}"
        groups: '["users", "wheel"]'

- name: push the blueprint into image builder
  osbuild.composer.push_blueprint:
    src: "{{ blueprint_src_path }}"

- name: start compose
  osbuild.composer.start_compose:
    blueprint: "my-rhel-edge-test"
    compose_type: "{{ compose_type }}"
  register: compose_start_out

- debug: var=compose_start_out

- name: wait for compose to finish
  osbuild.composer.wait_compose:
    compose_id: "{{ compose_start_out['result']['build_id'] }}"

- name: export the compose artifact
  osbuild.composer.export_compose:
    compose_id: "{{ compose_start_out['result']['build_id'] }}"
    dest: "/tmp/composer-compose.tar"

- name: download mycompose.tar
  ansible.posix.synchronize:
    mode: pull
    src: "/tmp/composer-compose.tar"
    dest: "/tmp/compose-{{ compose_start_out['result']['build_id'] }}.tar"
