---
version: 3

dependencies:
  ansible_core:
    package_pip: ansible-core>=2.15.4
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  system:
    - openssh-clients

images:
  base_image:
    name: registry.access.redhat.com/ubi9/ubi
