---
builder_blueprint_name: test_blueprint_aap
builder_blueprint_src_path: /tmp/blueprint.toml
builder_blueprint_distro_lower: "{{ 'rhel' if ansible_distribution == 'RedHat' else ansible_distribution | lower }}"
builder_blueprint_ref: "{{ builder_blueprint_distro_lower }}/{{ hostvars[inventory_hostname].ansible_distribution_major_version }}/x86_64/{{ 'iot' if ansible_distribution == 'Fedora' else 'edge' }}" # noqa yaml[line-length]
builder_compose_type: edge-commit
builder_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub', errors='warn') }}"
builder_compose_pkgs:
  - "vim-enhanced"
  - "git"
  - "ansible-core"
builder_compose_customizations:
  user:
    name: "core"
    description: "test user"
    password: "openshift"
    key: "{{ builder_pub_key }}"
    groups:
      - "users"
      - "wheel"
