---
galaxy_info:
  role_name: "populate_aap"
  standalone: false
  company: "Red Hat"
  description: >
    This role automates the process of populating AAP with infra.osbuild content
  author: Ansible Edge Working Group
  license: "GPL-3.0-or-later"
  min_ansible_version: "2.12"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - image
    - build
    - os
    - controller
    - aap
    - configuration

collections:
  - ansible.controller
  - redhat_cop.controller_configuration
dependencies: []
