objects:
  role: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module:
    create_blueprint:
      description: Create a new blueprint file
      name: create_blueprint
      namespace: ''
      version_added: null
    export_compose:
      description: Export successfully composed image from osbuild-composer service
      name: export_compose
      namespace: ''
      version_added: null
    get_all_finished_images:
      description: Returns all finished images
      name: get_all_finished_images
      namespace: ''
      version_added: null
    inject_ks:
      description: Inject Kickstart into composed ISO image.
      name: inject_ks
      namespace: ''
      version_added: null
    list_blueprints:
      description: Info module to get a list of blueprints from Weldr
      name: list_blueprints
      namespace: ''
      version_added: null
    push_blueprint:
      description: Push a blueprint file into composer
      name: push_blueprint
      namespace: ''
      version_added: null
    repository:
      description: Add source repository to add custom packages
      name: repository
      namespace: ''
      version_added: null
    rhsm_repo_info:
      description: Gather information about rhsm repositories
      name: rhsm_repo_info
      namespace: ''
      version_added: null
    start_compose:
      description: Start an ostree compose
      name: start_compose
      namespace: ''
      version_added: null
    wait_compose:
      description: Wait for a compose to complete
      name: wait_compose
      namespace: ''
      version_added: null
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 2.0.1
