---
# vars file for builder
builder_kickstart_options:
  - lang en_US.UTF-8
  - keyboard us
  - timezone Etc/UTC --utc
  - text
  - zerombr
  - clearpart --all --initlabel
  - autopart --type=plain --fstype=xfs --nohome
  - reboot
  - network --bootproto=dhcp
  - user --name={{ builder_compose_customizations['user']['name'] }} {{ "--password" if builder_password is defined  }} {{ builder_password if builder_password is defined }} --group=wheel,user  # noqa yaml[line-length]
  - services --enabled=ostree-remount
  - ostreesetup --nogpg --osname=rhel --remote=edge --url=http://{{ ansible_facts["default_ipv4"]["address"] }}/{{ builder_blueprint_name }}/commits/{{ blueprint_output['current_version'] }}/repo/ --ref={{ builder_blueprint_ref }} # noqa yaml[line-length]
