---
custom_repo_name: Everything
custom_repo_base_url: "https://dl.fedoraproject.org/pub/epel/{{ hostvars[inventory_hostname].ansible_distribution_major_version }}/Everything/x86_64/"
custom_repo_type: yum-baseurl
custom_repo_check_ssl: false
custom_repo_check_gpg: false
custom_repo_state: present
_infra_osbuild_ostree_os: false
base_packages:
  - rsync
  - osbuild-composer
  - composer-cli
  - cockpit-composer
  - bash-completion
  - firewalld
  - genisoimage
  - httpd
  - syslinux
  - cockpit
  - weldr-client
