---
# tasks file for system_info
- name: Get system info
  ansible.builtin.command: '/usr/bin/rpm-ostree status --json'
  register: rpm_ostree_status_output

- name: Set rpm-ostree facts on system
  vars:
    json_output: "{{ rpm_ostree_status_output.stdout | from_json }}"
  ansible.builtin.set_fact:
    cacheable: true
    rpm_ostree:
      - current:
          version: "{{ json_output['deployments'][0]['version'] }}"
          checksum: "{{ json_output['deployments'][0]['checksum'] }}"
      - rollback:
          version: "{{ json_output['deployments'][1]['version'] }}"
          checksum: "{{ json_output['deployments'][1]['checksum'] }}"
