---

- name: Get Package Facts
  ansible.builtin.package_facts:
    manager: auto

- name: Collect facts for the role
  ansible.builtin.setup:
    gather_subset: min

- name: Test for ostree-based OS
  ansible.builtin.shell:
    cmd: "set -eo pipefail rpm-ostree status | grep Deployments"
  register: _setup_server_infra_osbuild_ostree_check  # noqa var-naming[no-role-prefix]
  failed_when: false
  changed_when: false
  check_mode: false

- name: Run different steps if this is ostree based OS
  ansible.builtin.include_role:
    name: "{{ _setup_server_infra_osbuild_ostree_os | ternary('ostree.yml','no-ostree.yml') }}"


- name: Enable required systemd services
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: "{{ item }}"
  loop: "{{ __setup_server_required_systemd_services }}"

- name: Enable required Firewall services
  ansible.posix.firewalld:  # noqa only-builtins
    permanent: true
    immediate: true
    service: "{{ item }}"
    state: enabled
  loop: "{{ __setup_server_required_firewall_services }}"
