---
- name: Build Microshift Image
  hosts: all
  gather_facts: true
  vars:
    builder_blueprint_name: microshift
    builder_blueprint_src_path: "/tmp/microshift.toml"
    compose_type: edge-commit
    pubkey_file: "~/.ssh/id_rsa.pub"
    builder_custom_repos:
      - name: EPEL8
        base_url: "https://dl.fedoraproject.org/pub/epel/{{ hostvars[inventory_hostname].ansible_distribution_major_version }}/Everything/x86_64/"
        type: yum-baseurl
        check_ssl: true
        check_gpg: false
      - name: microshift
        base_url: https://download.copr.fedorainfracloud.org/results/@redhat-et/microshift-testing/epel-8-x86_64/
        type: yum-baseurl
        check_ssl: true
        check_gpg: false
      - name: microshift-deps
        base_url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rpms/4.12-el8-beta/
        type: yum-baseurl
        check_ssl: true
        check_gpg: false
    builder_compose_pkgs:
      - vim-enhanced
      - git
      - nano
      - microshift
      - NetworkManager-wifi
    builder_compose_customizations:
      user:
        name: "edge"
        description: "test user"
        password: "openshift"
        key: "{{ pubkey_file }}"
        groups: '["users", "wheel"]'
  tasks:
    - name: Run the setup server role
      ansible.builtin.import_role:
        name: infra.osbuild.setup_server
    - name: Run the builder role
      ansible.builtin.import_role:
        name: infra.osbuild.builder
