trigger:
  batch: true
  branches:
    include:
      - main
      - stable-*

pr:
  autoCancel: true
  branches:
    include:
      - main
      - stable-*

schedules:
  - cron: 0 9 * * *
    displayName: Nightly
    always: true
    branches:
      include:
        - main
        - stable-*

variables:
  - name: checkoutPath
    value: ansible_collections/infra/osbuild
  - name: coverageBranches
    value: main
  - name: pipelinesCoverage
    value: coverage
  - name: entryPoint
    value: tests/utils/shippable/shippable.sh
  - name: fetchDepth
    value: 0

resources:
  containers:
    - container: default
      image: quay.io/ansible/azure-pipelines-test-container:3.0.0

pool: Standard

stages:
## Sanity
  - stage: Sanity_devel
    displayName: Ansible devel sanity
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: '{0}'
          testFormat: 'devel/{0}'
          targets:
            - name: Sanity
              test: sanity
            - name: Units
              test: units
            - name: Lint
              test: lint
  - stage: Sanity_2_14
    displayName: Ansible 2.14 sanity
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: '{0}'
          testFormat: '2.14/{0}'
          targets:
            - name: Sanity
              test: sanity
            - name: Units
              test: units
  - stage: Sanity_2_13
    displayName: Ansible 2.13 sanity
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: '{0}'
          testFormat: '2.13/{0}'
          targets:
            - name: Sanity
              test: sanity
            - name: Units
              test: units
  - stage: Sanity_2_12
    displayName: Ansible 2.12 sanity
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: '{0}'
          testFormat: '2.12/{0}'
          targets:
            - name: Sanity
              test: sanity
            - name: Units
              test: units

## Remote tests
# choices of targets defined here:
#   https://github.com/ansible/ansible/blob/devel/test/lib/ansible_test/_data/completion/remote.txt
#
#   NOTE: defined targets vary by ansible-core branch
  - stage: Remote_devel
    displayName: Remote devel
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          testFormat: devel/{0}
          targets:
            - name: RHEL 9.0
              test: rhel/9.0
            - name: RHEL 8.6
              test: rhel/8.6
          groups:
            - 1
      - template: templates/matrix.yml
        parameters:
          testFormat: devel/{0}
          targets:
            - name: RHEL 9.0 ami
              test: rhel/9.0
            - name: RHEL 8.6 ami
              test: rhel/8.6
          groups:
            - 2
      - template: templates/matrix.yml
        parameters:
          testFormat: devel/{0}
          targets:
            - name: Fedora 36 container
              test: fedora/36
          groups:
            - 3
      - template: templates/matrix.yml
        parameters:
          testFormat: devel/{0}
          targets:
            - name: RHEL 9.0 edge-commit
              test: rhel/9.0
            - name: RHEL 8.6 edge-commit
              test: rhel/8.6
          groups:
            - 4
      - template: templates/matrix.yml
        parameters:
          testFormat: devel/{0}
          targets:
            - name: RHEL 9.0 edge-container
              test: rhel/9.0
            - name: RHEL 8.6 edge-container
              test: rhel/8.6
          groups:
            - 5
      - template: templates/matrix.yml
        parameters:
          testFormat: devel/{0}
          targets:
            - name: RHEL 9.0 edge-installer
              test: rhel/9.0
            - name: RHEL 8.6 edge-installer
              test: rhel/8.6
          groups:
            - 6
      - template: templates/matrix.yml
        parameters:
          testFormat: devel/{0}
          targets:
            - name: RHEL 9.0 edge-raw-image
              test: rhel/9.0
            - name: RHEL 8.6 edge-raw-image
              test: rhel/8.6
          groups:
            - 7

      # comment out because edge-simplified-installer requireds an installation device
      # - template: templates/matrix.yml
      #   parameters:
      #     testFormat: devel/{0}
      #     targets:
      #       - name: RHEL 9.0 edge-simplified-installer
      #         test: rhel/9.0
      #       - name: RHEL 8.6 edge-simplified-installer
      #         test: rhel/8.6
      #     groups:
      #       - 8
      - template: templates/matrix.yml
        parameters:
          testFormat: devel/{0}
          targets:
            - name: RHEL 9.0 image-installer
              test: rhel/9.0
            - name: RHEL 8.6 image-installer
              test: rhel/8.6
          groups:
            - 9
      - template: templates/matrix.yml
        parameters:
          testFormat: devel/{0}
          targets:
            - name: Fedora 36 iot-commit
              test: fedora/36
          groups:
            - 10
      - template: templates/matrix.yml
        parameters:
          testFormat: devel/{0}
          targets:
            - name: Fedora 36 iot-container
              test: fedora/36
          groups:
            - 11
      - template: templates/matrix.yml
        parameters:
          testFormat: devel/{0}
          targets:
            - name: Fedora 36 iot-installer
              test: fedora/36
          groups:
            - 12
      - template: templates/matrix.yml
        parameters:
          testFormat: devel/{0}
          targets:
            - name: Fedora 36 iot-raw-image
              test: fedora/36
          groups:
            - 13
      - template: templates/matrix.yml
        parameters:
          testFormat: devel/{0}
          targets:
            - name: RHEL 9.0 oci
              test: rhel/9.0
            - name: RHEL 8.6 oci
              test: rhel/8.6
          groups:
            - 14
      - template: templates/matrix.yml
        parameters:
          testFormat: devel/{0}
          targets:
            - name: RHEL 9.0 openstack
              test: rhel/9.0
            - name: RHEL 8.6 openstack
              test: rhel/8.6
          groups:
            - 15
      - template: templates/matrix.yml
        parameters:
          testFormat: devel/{0}
          targets:
            - name: RHEL 9.0 qcow2
              test: rhel/9.0
            - name: RHEL 8.6 qcow2
              test: rhel/8.6
          groups:
            - 16
      - template: templates/matrix.yml
        parameters:
          testFormat: devel/{0}
          targets:
            - name: RHEL 9.0 tar
              test: rhel/9.0
            - name: RHEL 8.6 tar
              test: rhel/8.6
          groups:
            - 17
      - template: templates/matrix.yml
        parameters:
          testFormat: devel/{0}
          targets:
            - name: RHEL 9.0 vhd
              test: rhel/9.0
            - name: RHEL 8.6 vhd
              test: rhel/8.6
          groups:
            - 18
      - template: templates/matrix.yml
        parameters:
          testFormat: devel/{0}
          targets:
            - name: RHEL 9.0 vmdk
              test: rhel/9.0
            - name: RHEL 8.6 vmdk
              test: rhel/8.6
          groups:
            - 19
  - stage: Remote_2_14
    displayName: Remote 2.14
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.14/{0}
          targets:
            - name: RHEL 9.0
              test: rhel/9.0
            - name: RHEL 8.6
              test: rhel/8.6
          groups:
            - 1
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.14/{0}
          targets:
            - name: RHEL 9.0 ami
              test: rhel/9.0
            - name: RHEL 8.6 ami
              test: rhel/8.6
          groups:
            - 2
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.14/{0}
          targets:
            - name: Fedora 36 container
              test: fedora/36
          groups:
            - 3
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.14/{0}
          targets:
            - name: RHEL 9.0 edge-commit
              test: rhel/9.0
            - name: RHEL 8.6 edge-commit
              test: rhel/8.6
          groups:
            - 4
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.14/{0}
          targets:
            - name: RHEL 9.0 edge-container
              test: rhel/9.0
            - name: RHEL 8.6 edge-container
              test: rhel/8.6
          groups:
            - 5
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.14/{0}
          targets:
            - name: RHEL 9.0 edge-installer
              test: rhel/9.0
            - name: RHEL 8.6 edge-installer
              test: rhel/8.6
          groups:
            - 6
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.14/{0}
          targets:
            - name: RHEL 9.0 edge-raw-image
              test: rhel/9.0
            - name: RHEL 8.6 edge-raw-image
              test: rhel/8.6
          groups:
            - 7

      # comment out because edge-simplified-installer requireds an installation device
      # - template: templates/matrix.yml
      #   parameters:
      #     testFormat: 2.14/{0}
      #     targets:
      #       - name: RHEL 9.0 edge-simplified-installer
      #         test: rhel/9.0
      #       - name: RHEL 8.6 edge-simplified-installer
      #         test: rhel/8.6
      #     groups:
      #       - 8
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.14/{0}
          targets:
            - name: RHEL 9.0 image-installer
              test: rhel/9.0
            - name: RHEL 8.6 image-installer
              test: rhel/8.6
          groups:
            - 9
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.14/{0}
          targets:
            - name: Fedora 36 iot-commit
              test: fedora/36
          groups:
            - 10
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.14/{0}
          targets:
            - name: Fedora 36 iot-container
              test: fedora/36
          groups:
            - 11
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.14/{0}
          targets:
            - name: Fedora 36 iot-installer
              test: fedora/36
          groups:
            - 12
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.14/{0}
          targets:
            - name: Fedora 36 iot-raw-image
              test: fedora/36
          groups:
            - 13
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.14/{0}
          targets:
            - name: RHEL 9.0 oci
              test: rhel/9.0
            - name: RHEL 8.6 oci
              test: rhel/8.6
          groups:
            - 14
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.14/{0}
          targets:
            - name: RHEL 9.0 openstack
              test: rhel/9.0
            - name: RHEL 8.6 openstack
              test: rhel/8.6
          groups:
            - 15
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.14/{0}
          targets:
            - name: RHEL 9.0 qcow2
              test: rhel/9.0
            - name: RHEL 8.6 qcow2
              test: rhel/8.6
          groups:
            - 16
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.14/{0}
          targets:
            - name: RHEL 9.0 tar
              test: rhel/9.0
            - name: RHEL 8.6 tar
              test: rhel/8.6
          groups:
            - 17
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.14/{0}
          targets:
            - name: RHEL 9.0 vhd
              test: rhel/9.0
            - name: RHEL 8.6 vhd
              test: rhel/8.6
          groups:
            - 18
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.14/{0}
          targets:
            - name: RHEL 9.0 vmdk
              test: rhel/9.0
            - name: RHEL 8.6 vmdk
              test: rhel/8.6
          groups:
            - 19
  - stage: Remote_2_13
    displayName: Remote 2.13
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.13/{0}
          targets:
            - name: RHEL 9.0
              test: rhel/9.0
            - name: RHEL 8.5
              test: rhel/8.5
          groups:
            - 1
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.13/{0}
          targets:
            - name: RHEL 9.0 ami
              test: rhel/9.0
            - name: RHEL 8.5 ami
              test: rhel/8.5
          groups:
            - 2
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.13/{0}
          targets:
            - name: RHEL 9.0 edge-commit
              test: rhel/9.0
            - name: RHEL 8.5 edge-commit
              test: rhel/8.5
          groups:
            - 4
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.13/{0}
          targets:
            - name: RHEL 9.0 edge-container
              test: rhel/9.0
            - name: RHEL 8.5 edge-container
              test: rhel/8.5
          groups:
            - 5
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.13/{0}
          targets:
            - name: RHEL 9.0 edge-installer
              test: rhel/9.0
            - name: RHEL 8.5 edge-installer
              test: rhel/8.5
          groups:
            - 6
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.13/{0}
          targets:
            - name: RHEL 9.0 edge-raw-image
              test: rhel/9.0
          groups:
            - 7

      # comment out because edge-simplified-installer requireds an installation device
      # - template: templates/matrix.yml
      #   parameters:
      #     testFormat: 2.13/{0}
      #     targets:
      #       - name: RHEL 9.0 edge-simplified-installer
      #         test: rhel/9.0
      #     groups:
      #       - 8
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.13/{0}
          targets:
            - name: RHEL 9.0 image-installer
              test: rhel/9.0
            - name: RHEL 8.5 image-installer
              test: rhel/8.5
          groups:
            - 9
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.13/{0}
          targets:
            - name: RHEL 9.0 oci
              test: rhel/9.0
            - name: RHEL 8.5 oci
              test: rhel/8.5
          groups:
            - 14
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.13/{0}
          targets:
            - name: RHEL 9.0 openstack
              test: rhel/9.0
            - name: RHEL 8.5 openstack
              test: rhel/8.5
          groups:
            - 15
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.13/{0}
          targets:
            - name: RHEL 9.0 qcow2
              test: rhel/9.0
            - name: RHEL 8.5 qcow2
              test: rhel/8.5
          groups:
            - 16
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.13/{0}
          targets:
            - name: RHEL 9.0 tar
              test: rhel/9.0
            - name: RHEL 8.5 tar
              test: rhel/8.5
          groups:
            - 17
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.13/{0}
          targets:
            - name: RHEL 9.0 vhd
              test: rhel/9.0
            - name: RHEL 8.5 vhd
              test: rhel/8.5
          groups:
            - 18
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.13/{0}
          targets:
            - name: RHEL 9.0 vmdk
              test: rhel/9.0
            - name: RHEL 8.5 vmdk
              test: rhel/8.5
          groups:
            - 19
  - stage: Remote_2_12
    displayName: Remote 2.12
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.12/{0}
          targets:
            - name: RHEL 8.4
              test: rhel/8.4
          groups:
            - 1
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.12/{0}
          targets:
            - name: RHEL 8.4 ami
              test: rhel/8.4
          groups:
            - 2
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.12/{0}
          targets:
            - name: RHEL 8.4 edge-commit
              test: rhel/8.4
          groups:
            - 4
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.12/{0}
          targets:
            - name: RHEL 8.4 edge-container
              test: rhel/8.4
          groups:
            - 5
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.12/{0}
          targets:
            - name: RHEL 8.4 edge-installer
              test: rhel/8.4
          groups:
            - 6
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.12/{0}
          targets:
            - name: RHEL 8.4 image-installer
              test: rhel/8.4
          groups:
            - 9
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.12/{0}
          targets:
            - name: RHEL 8.4 oci
              test: rhel/8.4
          groups:
            - 14
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.12/{0}
          targets:
            - name: RHEL 8.4 openstack
              test: rhel/8.4
          groups:
            - 15
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.12/{0}
          targets:
            - name: RHEL 8.4 qcow2
              test: rhel/8.4
          groups:
            - 16
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.12/{0}
          targets:
            - name: RHEL 8.4 tar
              test: rhel/8.4
          groups:
            - 17
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.12/{0}
          targets:
            - name: RHEL 8.4 vhd
              test: rhel/8.4
          groups:
            - 18
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.12/{0}
          targets:
            - name: RHEL 8.4 vmdk
              test: rhel/8.4
          groups:
            - 19


## Finally
  - stage: Summary
    condition: succeededOrFailed()
    dependsOn:
      - Sanity_devel
      - Sanity_2_14
      - Sanity_2_13
      - Sanity_2_12
      - Remote_devel
      - Remote_2_14
      - Remote_2_13
      - Remote_2_12
    jobs:
      - template: templates/coverage.yml
