trigger:
  batch: true
  branches:
    include:
      - main
      - stable-*

pr:
  autoCancel: true
  branches:
    include:
      - main
      - stable-*

schedules:
  - cron: 0 9 * * *
    displayName: Nightly
    always: true
    branches:
      include:
        - main
        - stable-*

variables:
  - name: checkoutPath
    value: ansible_collections/osbuild/composer
  - name: coverageBranches
    value: main
  - name: pipelinesCoverage
    value: coverage
  - name: entryPoint
    value: tests/utils/shippable/shippable.sh
  - name: fetchDepth
    value: 0

resources:
  containers:
    - container: default
      image: quay.io/ansible/azure-pipelines-test-container:3.0.0

pool: Standard

stages:
## Sanity
  - stage: Sanity_devel
    displayName: Ansible devel sanity
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: '{0}'
          testFormat: 'devel/{0}'
          targets:
            - name: Sanity
              test: sanity
            - name: Units
              test: units
  - stage: Sanity_2_14
    displayName: Ansible 2.14 sanity
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: '{0}'
          testFormat: '2.14/{0}'
          targets:
            - name: Sanity
              test: sanity
            - name: Units
              test: units
  - stage: Sanity_2_13
    displayName: Ansible 2.13 sanity
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: '{0}'
          testFormat: '2.13/{0}'
          targets:
            - name: Sanity
              test: sanity
            - name: Units
              test: units
  - stage: Sanity_2_12
    displayName: Ansible 2.12 sanity
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: '{0}'
          testFormat: '2.12/{0}'
          targets:
            - name: Sanity
              test: sanity
            - name: Units
              test: units

## Remote tests
# choices of targets defined here:
#   https://github.com/ansible/ansible/blob/devel/test/lib/ansible_test/_data/completion/remote.txt
#
#   NOTE: defined targets vary by ansible-core branch
  - stage: Remote_devel
    displayName: Remote devel
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          testFormat: devel/{0}
          targets:
            - name: RHEL 9.0
              test: rhel/9.0
            - name: RHEL 8.6
              test: rhel/8.6
          groups:
            - 1
  - stage: Remote_2_14
    displayName: Remote 2.14
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.14/{0}
          targets:
            - name: RHEL 9.0
              test: rhel/9.0
            - name: RHEL 8.6
              test: rhel/8.6
          groups:
            - 1
  - stage: Remote_2_13
    displayName: Remote 2.13
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.13/{0}
          targets:
            - name: RHEL 9.0
              test: rhel/9.0
            - name: RHEL 8.5
              test: rhel/8.5
          groups:
            - 1
  - stage: Remote_2_12
    displayName: Remote 2.12
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          testFormat: 2.12/{0}
          targets:
            - name: RHEL 8.4
              test: rhel/8.4
          groups:
            - 1


## Finally
  - stage: Summary
    condition: succeededOrFailed()
    dependsOn:
      - Sanity_devel
      - Sanity_2_14
      - Sanity_2_13
      - Sanity_2_12
      - Remote_devel
      - Remote_2_14
      - Remote_2_13
      - Remote_2_12
    jobs:
      - template: templates/coverage.yml
