---
- name: Debug
  ansible.builtin.debug:
    msg: "{{ item.name }}"
  loop: "{{ populate_aap_execution_environments }}"

- name: Set controller execution environments facts
  ansible.builtin.set_fact:
    controller_execution_environments:
      - name: "{{ item.name }}"
        new_name: "{{ item.new_name | default(None) }}"
        description: "{{ item.description | default(None) }}"
        image: "{{ item.image }}"
        organization: "{{ item.organization | default(None) }}"
        credential: "{{ item.credential | default(None) }}"
        pull: "{{ item.pull | default(None) }}"
        state: "{{ item.state | default('present') }}"
  loop: "{{ populate_aap_execution_environments }}"
  when: populate_aap_execution_environments is defined

- name: Set controller organizations facts
  ansible.builtin.set_fact:
    controller_organizations:
      - name: "{{ item.name }}"
        description: "{{ item.description | default(None) }}"
        custom_virtualenv: "{{ item.custom_virtualenv | default(None) }}"
        max_hosts: "{{ item.max_hosts | default(None) }}"
        instance_groups: "{{ item.instance_groups | default(None) }}"
        galaxy_credentials: "{{ item.galaxy_credentials | default(None) }}"
        default_environment: "{{ item.default_environment | default(None) }}"
        notification_templates_started: "{{ item.notification_templates_started | default(None) }}"
        notification_templates_success: "{{ item.notification_templates_success | default(None) }}"
        notification_templates_error: "{{ item.notification_templates_error | default(None) }}"
        notification_templates_approvals: "{{ item.notification_templates_approvals | default(None) }}"
        state: "{{ item.state | default(None) }}"
        assign_galaxy_credentials_to_org: "{{ item.assign_galaxy_credentials_to_org | default(None) }}"
        assign_default_ee_to_org: "{{ item.assign_default_ee_to_org | default(None) }}"
  loop: "{{ populate_aap_organizations }}"
  when: populate_aap_organizations is defined

- name: Set controller inventories facts
  ansible.builtin.set_fact:
    controller_inventories:
      - name: "{{ item.name }}"
        new_name: "{{ item.new_name | default(None) }}"
        copy_from: "{{ item.copy_from | default(None) }}"
        description: "{{ item.description | default(None) }}"
        organization: "{{ item.organization }}"
        instance_groups: "{{ item.instance_groups | default(None) }}"
        input_inventories: "{{ item.input_inventories | default(None) }}"
        variables: "{{ item.variables | default(None) }}"
        kind: "{{ item.kind | default(None) }}"
        host_filter: "{{ item.host_filter | default(None) }}"
        prevent_instance_group_fallback: "{{ item.prevent_instance_group_fallback | default(None) }}"
        state: "{{ item.state | default(None) }}"
  loop: "{{ populate_aap_inventories }}"
  when: populate_aap_inventories is defined

- name: Set controller hosts facts
  ansible.builtin.set_fact:
    controller_hosts:
      - name: "{{ item.name }}"
        new_name: "{{ item.new_name | default(None) }}"
        description: "{{ item.description | default(None) }}"
        inventory: "{{ item.inventory }}"
        enabled: "{{ item.enabled | default(None) }}"
        variables: "{{ item.variables | default(None) }}"
        state: "{{ item.state | default(None) }}"
  loop: "{{ populate_aap_hosts }}"
  when: populate_aap_hosts is defined

- name: Set controller projests facts
  ansible.builtin.set_fact:
    controller_projects:
      - name: "{{ item.name }}"
        new_name: "{{ item.new_name | default(None) }}"
        copy_from: "{{ item.copy_from | default(None) }}"
        description: "{{ item.description | default(None) }}"
        organization: "{{ item.organization }}"
        scm_type: "{{ item.scm_type | default(None) }}"
        scm_url: "{{ item.scm_url | default(None) }}"
        default_environment: "{{ item.default_environment | default(None) }}"
        local_path: "{{ item.local_path | default(None) }}"
        scm_branch: "{{ item.scm_branch | default(None) }}"
        scm_refspec: "{{ item.scm_refspec | default(None) }}"
        credential: "{{ item.credential | default(None) }}"
        signature_validation_credential: "{{ item.signature_validation_credential | default(None) }}"
        scm_clean: "{{ item.scm_clean | default(None) }}"
        scm_delete_on_update: "{{ item.scm_delete_on_update | default(None) }}"
        scm_track_submodules: "{{ item.scm_track_submodules | default(None) }}"
        scm_update_on_launch: "{{ item.scm_update_on_launch | default(None) }}"
        scm_update_cache_timeout: "{{ item.scm_update_cache_timeout | default(None) }}"
        allow_override: "{{ item.allow_override | default(None) }}"
        timeout: "{{ item.timeout | default(None) }}"
        custom_virtualenv: "{{ item.custom_virtualenv | default(None) }}"
        notification_templates_started: "{{ item.notification_templates_started | default(None) }}"
        notification_templates_success: "{{ item.notification_templates_success | default(None) }}"
        notification_templates_error: "{{ item.notification_templates_error | default(None) }}"
        state: "{{ item.state | default(None) }}"
        wait: "{{ item.wait | default(None) }}"
        update_project: "{{ item.update_project | default(None) }}"
        interval: "{{ item.interval | default(None) }}"
  loop: "{{ populate_aap_projects }}"
  when: populate_aap_projects is defined

- name: Set controller credentials facts
  ansible.builtin.set_fact:
    controller_credentials:
      - name: "{{ item.name }}"
        new_name: "{{ item.new_name | default(None) }}"
        copy_from: "{{ item.copy_from | default(None) }}"
        description: "{{ item.description | default(None) }}"
        organization: "{{ item.organization | default(None) }}"
        credential_type: "{{ item.credential_type | default(None) }}"
        inputs: "{{ item.inputs | default(None) }}"
        user: "{{ item.user | default(None) }}"
  loop: "{{ populate_aap_credentials }}"
  when: populate_aap_credentials is defined

- name: Set controller job templates facts
  ansible.builtin.set_fact:
    controller_templates:
      - name: "{{ item.name }}"
        new_name: "{{ item.new_name | default(None) }}"
        copy_from: "{{ item.copy_from | default(None) }}"
        description: "{{ item.description | default(None) }}"
        execution_environment: "{{ item.execution_environment | default(None) }}"
        job_type: "{{ item.job_type | default(None) }}"
        inventory: "{{ item.inventory | default(None) }}"
        organization: "{{ item.organization | default(None) }}"
        project: "{{ item.project | default(None) }}"
        playbook: "{{ item.playbook | default(None) }}"
        credentials: "{{ item.credentials | default(None) }}"
        fork: "{{ item.fork | default(None) }}"
        limit: "{{ item.limit | default(None) }}"
        verbosity: "{{ item.verbosity | default(None) }}"
        extra_vars: "{{ item.extra_vars | default(None) }}"
        job_tags: "{{ item.job_tags | default(None) }}"
        force_handlers: "{{ item.force_handlers | default(None) }}"
        skip_tags: "{{ item.skip_tags | default(None) }}"
        start_at_task: "{{ item.start_at_task | default(None) }}"
        diff_mode: "{{ item.diff_mode | default(None) }}"
        use_fact_cache: "{{ item.use_fact_cache | default(None) }}"
        host_config_key: "{{ item.host_config_key | default(None) }}"
        ask_scm_branch_on_launch: "{{ item.ask_scm_branch_on_launch | default(None) }}"
        ask_diff_mode_on_launch: "{{ item.ask_diff_mode_on_launch | default(None) }}"
        ask_variables_on_launch: "{{ item.ask_variables_on_launch | default(None) }}"
        ask_limit_on_launch: "{{ item.ask_limit_on_launch | default(None) }}"
        ask_tags_on_launch: "{{ item.ask_tags_on_launch | default(None) }}"
        ask_skip_tags_on_launch: "{{ item.ask_skip_tags_on_launch | default(None) }}"
        ask_job_type_on_launch: "{{ item.ask_job_type_on_launch | default(None) }}"
        ask_verbosity_on_launch: "{{ item.ask_verbosity_on_launch | default(None) }}"
        ask_inventory_on_launch: "{{ item.ask_inventory_on_launch | default(None) }}"
        ask_credential_on_launch: "{{ item.ask_credential_on_launch | default(None) }}"
        ask_execution_environment_on_launch: "{{ item.ask_execution_environment_on_launch | default(None) }}"
        ask_forks_on_launch: "{{ item.ask_forks_on_launch | default(None) }}"
        ask_instance_groups_on_launch: "{{ item.ask_instance_groups_on_launch | default(None) }}"
        ask_job_slice_count_on_launch: "{{ item.ask_job_slice_count_on_launch | default(None) }}"
        ask_labels_on_launch: "{{ item.ask_labels_on_launch | default(None) }}"
        ask_timeout_on_launch: "{{ item.ask_timeout_on_launch | default(None) }}"
        prevent_instance_group_fallback: "{{ item.prevent_instance_group_fallback | default(None) }}"
        survey_enabled: "{{ item.survey_enabled | default(None) }}"
        survey_spec: "{{ item.survey_spec | default(None) }}"
        survey: "{{ item.survey | default(None) }}"
        become_enabled: "{{ item.become_enabled | default(None) }}"
        allow_simultaneous: "{{ item.allow_simultaneous | default(None) }}"
        timeout: "{{ item.timeout | default(None) }}"
        instance_groups: "{{ item.instance_groups | default(None) }}"
        job_slice_count: "{{ item.job_slice_count | default(None) }}"
        webhook_service: "{{ item.webhook_service | default(None) }}"
        webhook_credential: "{{ item.webhook_credential | default(None) }}"
        scm_branch: "{{ item.scm_branch | default(None) }}"
        labels: "{{ item.labels | default(None) }}"
        custom_virtualenv: "{{ item.custom_virtualenv | default(None) }}"
        notification_templates_started: "{{ item.notification_templates_started | default(None) }}"
        notification_templates_success: "{{ item.notification_templates_success | default(None) }}"
        notification_templates_error: "{{ item.notification_templates_error | default(None) }}"
        state: "{{ item.state | default(None) }}"
  loop: "{{ populate_aap_job_templates }}"
  when: populate_aap_job_templates is defined

- name: Configure execution enviornment for AAP
  ansible.builtin.include_role:
    name: redhat_cop.controller_configuration.execution_environments
  when: controller_execution_environments is defined

- name: Configure Organizations
  ansible.builtin.include_role:
    name: redhat_cop.controller_configuration.organizations
  when: controller_organizations is defined

- name: Configure inventory
  ansible.builtin.include_role:
    name: redhat_cop.controller_configuration.inventories
  when: controller_inventories is defined

- name: Configure hosts
  ansible.builtin.include_role:
    name: redhat_cop.controller_configuration.hosts
  when: controller_hosts is defined

- name: Configure Projects
  ansible.builtin.include_role:
    name: redhat_cop.controller_configuration.projects
  when: controller_projects is defined

- name: Configure Looped Credentials
  ansible.builtin.include_role:
    name: redhat_cop.controller_configuration.credentials
  when: controller_credentials is defined

- name: Configure Job Templates
  ansible.builtin.include_role:
    name: redhat_cop.controller_configuration.job_templates
  when: controller_templates is defined
